### ISSUE TITLE
AttributeError: 'PDFGraphicState' object has no attribute 'fill_color'

### ISSUE THREAD

**Issue by hokieirish** [felipeochoa/minecart#39]
I'm trying to use minecart in Python3 using the two lines below.

`doc = minecart.Document(open(curFile, 'rb'))`
`page = doc.get_page(0)`

When I call get_page I get the following error message: AttributeError: 'PDFGraphicState' object has no attribute 'fill_color'

What would cause this and how can I fix it? I've used minecart before without issue. This is a new problem.

**Comment by felipeochoa** [comment]
I would guess you have the wrong version of pdfminer installed. There has been some discussion on other issues around how you can get the right version

**Comment by hokieirish** [comment]
Which version should I be using? And why would it have it worked previously?

I've tried reinstalling pdfminer3k.

**Comment by felipeochoa** [comment]
The 2 to 3 transition for pdfminer was messy. There were competing packages, some of which introduced breaking changes. If another package you are using depends on the wrong pdfminer package, the imports here will pull that in instead of the correct one. IIRC there was also an issue with conda installing the wrong version
